# Generated by Django 4.2.5 on 2023-10-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('country', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('last_edited_time', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=400)),
                ('longitude', models.CharField(max_length=400)),
                ('place_id', models.CharField(max_length=400)),
            ],
        ),
    ]
