# Generated by Django 4.2.5 on 2023-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_game_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='clue',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
