# Generated by Django 4.2.6 on 2023-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_game_is_approved_remove_game_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
