# Generated by Django 4.2.6 on 2023-11-04 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_location_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='looked_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.game'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hint',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
