# Generated by Django 4.2.5 on 2023-11-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_location_looked_by_admin_alter_location_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='looked_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
