# Generated by Django 4.2.5 on 2023-11-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_game_is_approved_game_looked_by_admin_game_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='is_approved',
            new_name='is_found',
        ),
        migrations.RemoveField(
            model_name='location',
            name='looked_by_admin',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user_id',
        ),
    ]
