# Generated by Django 4.2.6 on 2023-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_is_approved_location_is_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.CharField(max_length=400, null=True, verbose_name='Game Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=400, verbose_name='Game Name'),
        ),
    ]
